### PR TITLE
feat(digit-only): add min & max

### PR DESCRIPTION
**Pull request by tonivj5**
It partly fixes https://github.com/changhuixu/ngx-digit-only/issues/23 because implements the logic to prevent from input numbers bigger than `max` and smaller than `min` (only positive numbers because `-` is not allowed without `pattern`).

In other PR could be implemented this and allow negative numbers `-` (w/o patterns)
> If the user types 0 then is it possible to change the value from 0 to 1

### CODE REVIEW

**Comment by changhuixu** [comment]
Hi @tonivj5 , your pull request looks good to me.
Could you add examples in the app component?

**Comment by tonivj5** [comment]
I added an example in the [app component](https://github.com/changhuixu/ngx-digit-only/pull/31/files#diff-465e9f13ce23ec4a1e366935273fdbb6R7)

Do you mean more examples?

**Comment by changhuixu** [comment]
Sorry, I missed your example input. 
Could you update the input `id` to a different one? Otherwise, the e2e tests will see conflicts in IDs. It would be better if you can add Cypress tests for this feature. If not, then I will add e2e tests later.

Also, along the line of your another pull request, could you justify why we need to detect the changes for `min` and `max`?
I am thinking of this question for another two existing input parameters as well. I don't see the reason why an input field will change the `decimal` attribute and `decimalSeparator` attribute. I plan to use the `@Attribute` decorator for them, instead of using the `@Input()` decorator, in order to reduce some change detection. But it's just a thought.

**Comment by tonivj5** [comment]
> Could you update the input id to a different one? Otherwise, the e2e tests will see conflicts in IDs. It would be better if you can add Cypress tests for this feature. If not, then I will add e2e tests later.

Oh, good catch! I will add some e2e tests! :+1:

> Also, along the line of your another pull request, could you justify why we need to detect the changes for min and max?
I have added my use case [in the other PR](https://github.com/changhuixu/ngx-digit-only/pull/30#issuecomment-620096057) :eyes:

> I am thinking of this question for another two existing input parameters as well. I don't see the reason why an input field will change the decimal attribute and decimalSeparator attribute. I plan to use the @Attribute decorator for them, instead of using the @Input() decorator, in order to reduce some change detection. But it's just a thought.

This would make the component unusable for me, because I want to wrap it to reuse it in other components, adding my custom logic. Also, it breaks any type of dynamic behavior: change `min` and `max` in runtime (using a slider, for example), configuration of `decimalSeparator` based on location, etc.

I think the component should be reactive and be able of works with binding, I think it's Angular way and the most natural behavior.

**Comment by changhuixu** [comment]
Sounds good. Thanks for pointing out the guide of the `@Attribute` decorator from codelyzer.

**Comment by tonivj5** [comment]
> Could you update the input id to a different one?

Done :+1: 

> It would be better if you can add Cypress tests for this feature

Done :+1:

Should I do anything else?

**Pull request merged**
