### PR TITLE
DigitsOnly now supports decimal numbers

### PR DESCRIPTION
**Pull request by lakshman53**
i have modified the directive to accept a single decimal while data entry and ignore the paste or drop event if the content has more than one decimal.

check it and merge

### CODE REVIEW

**Comment by lakshman53** [comment]
Thanks for the inputs.

**Comment by changhuixu** [comment]
@lakshman53 Could you make the change? Then I will merge this branch. Thank you.

**Comment by lakshman53** [comment]
The activity is now complete

**Comment by lakshman53** [comment]
In the next version we need to focus on a flag which will be used to the data that needs to be entered (currency or cvv number of credit cards etc).

Amounts will have decimals and cc & cvv numbers will not have decimals

**Comment by changhuixu** [comment]
I have updated the code and README.
Would you like to take a look before I release 1.1.0?

**Pull request merged**
