### PR TITLE
feat(digit-only): allow pattern binding

### PR DESCRIPTION
**Pull request by tonivj5**
Allow to use pattern as a binding. It allows to change the pattern using an observable (`[pattern]="patterns$ | async"`) or simply change pattern on runtime (`this.pattern = otherPattern`).

### CODE REVIEW

**Comment by changhuixu** [comment]
Thank you. Could you give us some use cases when the `pattern` attribute needs to be changed?

**Comment by tonivj5** [comment]
For example:
- Set pattern by a simply binding (pattern comes from @Input, from config object, etc.)
```ts
// Example
@Component({
	template: `
		<input digitOnly [pattern]="pattern" />
	`,
})
class XComponent {
	pattern = 'xxxx';
}
```
- pattern comes from an observable (it may be async).
- Depending on a value, to use a pattern or other
```ts
// Example
@Component({
	template: `
		<checkbox (change)="changePattern($event) />
		<input digitOnly [pattern]="pattern" />
	`,
})
class XComponent {
	changePattern(allowNegatives: boolean) {
		this.pattern = patterns[allowNegatives];
	}
}
```
- Connect pattern to a formControl
```ts
// Example
@Component({
	template: `
		<checkbox [formControl]="control" />
		<input digitOnly [pattern]="pattern$" />
	`,
})
class XComponent {
	control = new FormControl(false);
	pattern$ = this.control.valueChanges.pipe(
					map(active => active ? patternOne : patternTwo)
				);
}
```
- Any other kind of dynamic behavior

**Comment by changhuixu** [comment]
Yes, I see how to use the binding. 
In addition to that, could you elaborate on the real-world scenarios? Why do developers want the input element to bind a dynamic `pattern`? 
I want to understand the purpose of this feature, so that we can see if we need to add a layer of change detection for this attribute.

**Comment by tonivj5** [comment]
Sure! I can show a fragment of my personal use case:
```ts
@Component({
	...
	template: `
		<div class="form-control-group">
          <label class="label" >
            {{ config.label }}
          </label>
          <input
			digitOnly
			[pattern]="config.pattern"
            [placeholder]="config.placeholder"
            class="form-control"
			...
          />
        </div>
	`,
})
class DigitInputComponent {
	...
	@Input()
	config: { pattern: string; label: string; placeholder?: string }
	...
}
```

This code doesn't work because the pattern hasn't any kind of binding to `regex` property, which it's being setting in the [constructor](https://github.com/changhuixu/ngx-digit-only/blob/master/projects/uiowa/digit-only/src/lib/digit-only.directive.ts#L30).

**Comment by changhuixu** [comment]
Good. 

I have a couple of questions. In your example, the `pattern` property doesn't need to be updated in later stages, right? Why couldn't you use existing input `pattern` attribute, if the value is a string?
And a side question, I saw you omitted the `new` keyword for `RegExp` in the `ngOnChanges` method. I know it works, but is there a reason? 

I am going to merge this pull request. But could you add another example for binding a `RegExp` object to the `pattern` input? 

Same to your other pull request, it would be better that you could add some Cypress tests. If not, I will add e2e tests later. No obligation. Thanks a lot.

**Comment by tonivj5** [comment]
> the pattern property doesn't need to be updated in later stages, right?

If my `config` object changes, `pattern` could change.

> Why couldn't you use existing input pattern attribute, if the value is a string?

Do you mean why `[pattern]="config.pattern"` doesn't work if `config.pattern` is a string?

> And a side question, I saw you omitted the new keyword for RegExp in the ngOnChanges method. I know it works, but is there a reason?

It's because `RegExp(pattern)` is a bit more performant if the `pattern` is already a `RegExp` instance (it returns `pattern` directly, not a new instance : `RegExp(pattern) === pattern`). But, no matter if you prefer `new RegExp`. I can change it :+1:

> But could you add another example for binding a RegExp object to the pattern input?

I have added this behavior because as you already work with a `RegExp` instance (internally), I thought it may be interesting to allow a `RegExp`. No problem if you prefer to revert it, up to you :+1:

> Same to your other pull request, it would be better that you could add some Cypress tests

Yeah, I will add it :test_tube:

**Comment by tonivj5** [comment]
> I am going to merge this pull request. But could you add another example for binding a RegExp object to the pattern input?

I have added `decimalPattern` which is a `RegExp` instance.

> Same to your other pull request, it would be better that you could add some Cypress tests.

I have added some tests. I hope they looks well :+1:

**Pull request merged**
