### PR TITLE
Do not allow digit addition on paste or drop

### PR DESCRIPTION
**Pull request by loicgasser**
Steps to reproduce:

- copy paste `25.13` twice on `decimal` enabled input.

Result:
The value in the input field is
`25.1325.13`

Expected Result:
The value in the input field is
`25.132513`

### CODE REVIEW

**Comment by changhuixu** [comment]
@loicgasser , Thanks a lot for your pull request. I realize that it is a bug 
I tested with your changes. It failed when a decimal number is pasted to an input box without decimal point set up.
e.g., enter `1.2` in the second input box in the demo page, then copy `1.2` to the first input box in the demo page. You will find that the first input box accepts `1.2`, while it shouldn't.

I have updated the code to address the duplicate decimal separator issue, and released v1.4.0.
Could you take a look? 

I will keep this pull request open, in case you find other issues and want to update.
Thanks again.

**Comment by loicgasser** [comment]
ok I missed that.
I can fix it.
I think you don't account for the selection.
In the second input box on your page:

1. Enter 1.1
2. Select with Ctrl + A
3. Paste 2.2 (previously copied)

Result:
22

It works on this branch.

FYI I have written some tests in own repository, I think it would be good to write some here as well, as it would be easier to systematically try all these use cases.

Do you know what testing framework you would like to use?

**Comment by loicgasser** [comment]
I use jest with jsdom, you could go with chrome headless

**Comment by loicgasser** [comment]
it's fixed

**Comment by loicgasser** [comment]
I found another bug.

1. Paste `11..22` in the second field

Result:
1122

Expected Result:
11.22

I think we should only keep the first dot.

In this branch, the result is `11..22`.

I don't really care because in my private repo I added:

```typescript
  @Input() decimals: number;
  @HostListener('blur', ['$event'])
  onBlur(e: any): void {
    const value = parseFloat(this.inputElement.value);
    if (this._isNumeric(value)) {
      this.inputElement.value = value.toFixed(this.decimals);
    }
  }

  private _isNumeric(value: number): boolean {
    return !isNaN(value) && isFinite(value);
  }
```

which will remove the extra dot on blur. (it would also remove the extra trailing 0 at the beginning).
But what I want is formatting the result with 2 digits after the `dot`. I do not know if this is a feature you are interested in.

**Comment by changhuixu** [comment]
If it is possible, could you add e2e tests using cypress? This is the way I am planning to go.
If you don't have time, then I will add e2e tests this month or next.

Yes, changing 11..22 to 1122 is expected.

**Comment by changhuixu** [comment]
I realize that e2e test on copy & paste events are not so friendly in Cypress. I now remember why I deleted protractor tests before. I was not able to write e2e tests about clipboard...

**Comment by loicgasser** [comment]
What I do is that I paste it pragmatically.

Here is what I have, you can probably adapt.

```javascript
import { TestBed, ComponentFixture, async } from '@angular/core/testing';
import { Component } from '@angular/core';

import { NumberOnlyDirective } from './number-only.directive';
import { createGenericTestComponent } from 'src/test/common';
import { By } from '@angular/platform-browser';

export function createGenericTestComponent<T>(
  html: string, type: new(...args: any[]) => T, detectChanges = true): ComponentFixture<T> {
  TestBed.overrideComponent(type, { set: { template: html } });
  const fixture = TestBed.createComponent(type);
  if (detectChanges) {
    fixture.detectChanges();
  }
  return fixture as ComponentFixture<T>;
}

@Component({
  selector: 'app-test-component',
  template: ''
})
export class TestComponent { }

const createFakePasteEvent = (value: string): any => {
  return {
    clipboardData: {
      getData: (contentType: string) => {
        return value;
      }
    },
    preventDefault: jest.fn()
  };
};

describe('appNumberOnly', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        TestComponent,
        NumberOnlyDirective
      ]
    });
  }));

  it('should only paste numbers per default', async(() => {
    const html = `
      <input type="text" appNumberOnly>
    `;
    const fixture = createGenericTestComponent(html, TestComponent);
    expect(fixture.componentInstance).toBeTruthy();

    const el = fixture.nativeElement.querySelector('input');
    const directiveEl = fixture.debugElement.query(By.directive(NumberOnlyDirective));
    const directiveInstance = directiveEl.injector.get(NumberOnlyDirective);

    // ClipboardEvent is not implemented in jsdom
    directiveInstance.onPaste(createFakePasteEvent('1'));
    expect(el.value).toEqual('1');

    directiveInstance.onPaste(createFakePasteEvent('12a!P'));
    expect(el.value).toEqual('112');

    // Do not paste the dot
    directiveInstance.onPaste(createFakePasteEvent('aW@.1!P'));
    expect(el.value).toEqual('1121');
  }));

  it('should paste numbers with at most 1 separator', async(() => {
    const html = `
      <input type="text" appNumberOnly [decimal]="true">
    `;
    const fixture = createGenericTestComponent(html, TestComponent);
    expect(fixture.componentInstance).toBeTruthy();

    const el = fixture.nativeElement.querySelector('input');
    const directiveEl = fixture.debugElement.query(By.directive(NumberOnlyDirective));
    const directiveInstance = directiveEl.injector.get(NumberOnlyDirective);

    // ClipboardEvent is not implemented in jsdom
    directiveInstance.onPaste(createFakePasteEvent('1.1'));
    expect(el.value).toEqual('1.1');

    directiveInstance.onPaste(createFakePasteEvent('.'));
    expect(el.value).toEqual('1.1');

    directiveInstance.onPaste(createFakePasteEvent('aW@.1!P'));
    expect(el.value).toEqual('1.11');

    // select text
    el.select();
    directiveInstance.onPaste(createFakePasteEvent('2.22'));
    expect(el.value).toEqual('2.22');

    el.select();
    directiveInstance.onPaste(createFakePasteEvent('33'));
    expect(el.value).toEqual('33');
  }));
});

```

**Comment by changhuixu** [comment]
Thank you @loicgasser . I have added e2e tests using cypress for this project, and the tests will run in CI on master branch. 

Thank you very much for your help and your name is recognized in the [v1.4.0 release](https://github.com/changhuixu/ngx-digit-only/releases/tag/v1.4.0).  I'd like to merge your code but I didn't find the necessity of code changes based on the current master branch, so I will close this pull request.

**Comment by loicgasser** [comment]
Sure I understand, your code was very useful in the first place. I just wanted to give back.

In the second input box on your page:

Enter 1.1
Select with Ctrl + A
Paste 2.2 (previously copied)
Result:
22

Have you fixed this bug?

**Comment by changhuixu** [comment]
Ahh, sorry I didn't get this one done. Now I see the reason of your changes.
I have updated code and added e2e tests with input selections.
I will release a new version of this package later.

**Pull request closed without merging**
